name: Continuous Deployment - STG

on:
  pull_request:
    branches:
        - release/*      

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: stg
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Deploy para Staging
        run: |
          echo "Fazendo deploy para Staging..."
