name: CD-Staging

on:
  push:
    branches:
      - release/*

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: stg
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Aprovação manual necessária
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy para Staging
        run: |
          echo "Fazendo deploy para Staging..."
