name: Continuous Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Escolha o ambiente para deploy'
        type: choice
        required: true        
        options:
          - dev
          - stg
          - prd

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Verificar tag e executar
        if: startsWith(github.event.inputs.tag, 'v')  
        run: |
          echo "Disparando o workflow para a tag ${GITHUB_REF}"
          
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Extract tag name
        run: echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Deploy para Produção
        run: |
          echo "Fazendo deploy para Produção..."
          echo $GIT_TAG
